export const FluidNames = [
    "Ammonia",
    "Leaded Gasoline",
    "GasolineE10",
    "Hydrofluoric Acid",
    "Boric Acid",
    "Hydrochloric Acid",
    "Acetic Acid",
    "Tetraethyllead",
    "Gasoline",
    "Machine Oil",
    "Sulfuric Acid",
    "Liquid Argon",
    "Liquid Nitrogen",
    "Liquid Oxygen",
    "Refined Diesel",
    "Diesel",
    "Ethanol",
    "LNG",
    "Poor Quality Diesel",
    "Concentrated Salt Solution",
    "Crude Diesel",
    "Liquid Glass",
    "Lithium Brine",
    "Molten Ferroaluminium Alloy",
    "Molten Purple Gold",
    "Sodium Hydroxide Solution",
    "Chlorine",
    "Hydrogen",
    "Oxygen",
    "Distilled Water",
    "Crude Oil",
    "Ethylene",
    "Filtered Water",
    "Fracking Oil",
    "Heavy Oil",
    "MEG",
    "Paraxylene",
    "PTA",
    "Light Oil",
    "Naphtha",
    "Refined Gas",
    "Argon",
    "Condensate",
    "Contaminated Water",
    "Depleted UF6 Waste",
    "Enriched UF6 Gas",
    "Exhaust",
    "High Pressure Steam",
    "Hot Crude Oil",
    "Hydrogen Sulfide",
    "Liquid Aluminium",
    "Liquid Brass",
    "Liquid Copper",
    "Liquid Gold",
    "Liquid Iron",
    "Liquid Lead",
    "Liquid Sulfur",
    "Low Pressure Steam",
    "Nitrogen",
    "Phosphorus Oxychloride",
    "Raw Gas",
    "Residue",
    "Slightly Enriched UF6 Gas",
    "Steam",
    "Sulfur Dioxide",
    "Sulfur Trioxide",
    "Tributyl Phosphate",
    "Unenriched UF6 Gas",
    "Water",
    "Water-Free Gas",
];